version: '3.7'

services:
  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: replaceme
    ports:
      - 3306:3306
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    ports:
      - 6543:6543
    environment:
      PYTHONUNBUFFERED: 'false'
